---
title: "Here and File Architecture Setup"
author: "Katie Emberley, Jonathan Nelson, and Annie Lackey"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document: 
    toc: yes
    toc_depth: 3
    toc_float: true
    number_sections: yes
    theme: bootstrap
    df_print: paged
    code_folding: hide
    highlight: pygments
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load new packages, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}
if (!require("here")) {install.packages("here"); require("here")}
```


# Create .here file to orient files to relative directory
```{r, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE}
here::set_here()
#Check where here directory
here()
```

# Setup file architecture
```{r, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE}
#Setup file architecture to place files from GEO and have output folder
GEO <- "GEO"
CellRanger <-"Cell Ranger"
Outputs <- "Outputs"
QC <- "QC Objects"
DTO <- "Doublet Detector Objects"
Intermediate <- "Intermediate Objects"
Subclusters <- "Subclusters"
DEGs <- "DEGs"
MG_Sub_DEGs <- "Microglia Subclustering DEGs"

#Create Folders for Sox10 Cre Postive and Negative and PLP Cre Positive and Negative GEO Datasets
if (!dir.exists(here(GEO))) {dir.create(here(GEO))}
if (!dir.exists(here("GEO", CellRanger))) {dir.create(here("GEO", CellRanger))}
#Create Outputs Folder and Outputs Subfolder
if (!dir.exists(here(Outputs))) {dir.create(here(Outputs))}
if (!dir.exists(here("Outputs", QC))) {dir.create(here("Outputs", QC))}
if (!dir.exists(here("Outputs", "QC Objects", DTO))) {dir.create(here("Outputs", "QC Objects", DTO))}
if (!dir.exists(here("Outputs", Subclusters))) {dir.create(here("Outputs", Subclusters))}
if (!dir.exists(here("Outputs", Intermediate))) {dir.create(here("Outputs", Intermediate))}
if (!dir.exists(here("Outputs", DEGs))) {dir.create(here("Outputs", DEGs))}
if (!dir.exists(here("Outputs", "DEGs", MG_Sub_DEGs))) {dir.create(here("Outputs", "DEGs", MG_Sub_DEGs))}

rm(list = ls())
```


# Session Info

```{r, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE}
sessionInfo()
```