---
title: "Optic Nerve Pre-Processing and Analysis Sequential Knit"
author: "Katie Emberley"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document: 
    toc: yes
    toc_depth: 3
    toc_float: true
    number_sections: yes
    theme: bootstrap
    df_print: paged
    code_folding: hide
    highlight: pygments
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load new packages, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

if (!require("knitr")) {install.packages("knitr"); require("knitr")}
if (!require("here")) {install.packages("here"); require("here")}
if (!require("dplyr")) {install.packages("dplyr"); require("dplyr")}
here()
```

```{r message = F}
#Knit all of the pre-processing files
rmarkdown::render(here("Code", "Pre-processing", "KFE_ON_1_Ambient RNA Filtering and DF.Rmd"))
rmarkdown::render(here("Code", "Pre-processing", "KFE_ON_2_Ambient RNA Filtering and DF.Rmd"))
rmarkdown::render(here("Code", "Pre-processing", "KFE_ON_3_Ambient RNA Filtering and DF.Rmd"))
rmarkdown::render(here("Code", "Pre-processing", "KFE_ON_4_Ambient RNA Filtering and DF.Rmd"))
rmarkdown::render(here("Code", "Pre-processing", "KFE_ON_5_Ambient RNA Filtering and DF.Rmd"))
rmarkdown::render(here("Code", "Pre-processing", "KFE_ON_6_Ambient RNA Filtering and DF.Rmd"))
rmarkdown::render(here("Code", "Pre-processing", "KFE_ON_7_Ambient RNA Filtering and DF.Rmd"))
rmarkdown::render(here("Code", "Pre-processing", "KFE_ON_8_Ambient RNA Filtering and DF.Rmd"))

#Knit the subsetting and integration file
rmarkdown::render(here("Code", "ON Integration and Subsetting.Rmd"))

##OPTIONAL

#Knit the DEG Files
rmarkdown::render(here("Code", "Analysis", "DEG Code", "ON_Combined Cluster Defining DEGs.Rmd"))
rmarkdown::render(here("Code", "Analysis", "DEG Code", "ON_Combined Het vs Control DEGs.Rmd"))
rmarkdown::render(here("Code", "Analysis", "DEG Code", "ON_Combined PLP Cre DEGs.Rmd"))
rmarkdown::render(here("Code", "Analysis", "DEG Code", "ON_Combined PLP Cre vs Sox10 Cre DEGs.Rmd"))
rmarkdown::render(here("Code", "Analysis", "DEG Code", "ON_Combined Sox10 Cre DEGs.Rmd"))

#Knit the Subclustering Oligolineage
rmarkdown::render(here("Code", "Analysis", "Oligolineage Subclustering Code", "ON_Combined_Oligos.Rmd"))

#Knit the Microglia Subclustering Files
rmarkdown::render(here("Code", "Analysis", "Microglia Subclustering Code", "ON_Combined_Microglia.Rmd"))
rmarkdown::render(here("Code", "Analysis", "Microglia Subclustering Code", "ON_Combined_Microglia_DEGs.Rmd"))
rmarkdown::render(here("Code", "Analysis", "Microglia Subclustering Code", "ON_Combined_Microglia_DEG_Pathways Analysis.Rmd"))
rmarkdown::render(here("Code", "Analysis", "ON_Combined_Microglia_Psuedolineage Analysis.Rmd"))
```


# Session Info
```{r, echo=TRUE, warning=FALSE, error=FALSE, message=FALSE}
sessionInfo()
```


  